### ISSUE TITLE
Numeric prefix of chapters don't exist in Docker images

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/book#340]
I ran the Docker images 

```bash
docker run -p 8888:8888 paddlepaddle/book
```

and got the following content in my Web browser:

![screen shot 2017-07-09 at 5 18 53 pm](https://user-images.githubusercontent.com/1548775/27998914-1c1d6de0-64cb-11e7-9c70-9655d9e9cc77.png)

We see that the directory prefixes like `00.`, `01.` etc do not exist in the Docker image.

These prefixes are important because they direct Jupyter Notebook to sort directories in the order of book chapters.

**Comment by wangkuiyi** [comment]
I tried to get into the running book container and confirmed that the directories in `/book` do not have numeric prefixes.

```
$ docker exec -i -t festive_gates /bin/bash
root@e40a99ceab09:/# ls /book
fit_a_line	      image_qa		  index.html.json	pre-commit-hooks    recommender_system	understand_sentiment
gan		      index.en.html	  index.html.tmpl	query_relationship  skip_thought	word2vec
image_caption	      index.en.html.json  label_semantic_roles	README.en.md	    speech_recognition
image_classification  index.en.html.tmpl  machine_translation	README.md	    tools
image_detection       index.html	  paddle		recognize_digits    travis
```

**Comment by wangkuiyi** [comment]
I browsed the script that builds the Docker image.  It seems that it runs a COPY directive at https://github.com/PaddlePaddle/book/blob/develop/.tools/build_docker.sh#L50.  But I am not sure what is the `.` (current directory) would be when we run this script.  I am also not sure who would run above script.

**Comment by typhoonzero** [comment]
Seems that we didn't build and push the latest book image to dockerhub.

**Comment by gangliao** [comment]
@wangkuiyi  build_docker.sh will be executed by TeamCity. I am curious which version of `Book` you use here.

**Comment by wangkuiyi** [comment]
@gangliao   It is weird!

```
root@e40a99ceab09:/# paddle version
PaddlePaddle 0.9.0a0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk: 
```
